[phases.setup]
cmds = [
  # download Hugo tarball
  "curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.149.0/hugo_extended_withdeploy_0.149.0_linux-amd64.tar.gz",
  
  # extract and install
  "tar -xzf hugo.tar.gz",
  "mv hugo /usr/local/bin/hugo",
]

[phases.build]
cmds = ["hugo --minify"]

[environment]
HUGO_VERSION = "0.149.0"

[[nixpacks.included_files]]
paths = ["/public"]
