[phases.setup]
aptPkgs = ["hugo"]
cmds = [
  "git submodule update --init --recursive"
]

[phases.build]
cmds = ["hugo --minify"]

[environment]
HUGO_VERSION = "0.149.0"

[[nixpacks.included_files]]
paths = ["/public"]
